---
title: "Linear Models"
author: "Dionna Attinson"
date: "11/7/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)
```

##This changed our reference to the variable level with least amount of values
```{r} 
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(
    boro = fct_infreq(boro),
    room_type = fct_infreq(room_type))
```

```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)
```

```{r, eval=FALSE}
fit 

summary(fit)
summary(fit)$coef
coef(fit)
```

```{r}
fit %>% 
  broom::glance()
fit %>% 
  broom::tidy()
```

```{r}
fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(term = str_replace(term, "^boro", "Boro: ")) %>% 
  knitr::kable(digits = 3)
```

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(
    boro = fct_infreq(boro),
    room_type = fct_infreq(room_type))
```

```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)

fit %>% 
  broom::tidy()
```

## Diagnostics for linear regression models 
##### Diagnostics for linear regression models is almost always looking at residuals. Sometimes you also want to look at the fitted values.

```{r} 
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = boro, y = resid)) + 
  geom_violin() 

modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = stars, y = resid)) + 
  geom_point() 

modelr::add_predictions(nyc_airbnb, fit)
```

## Nesting 
```{r}
fit_interaction = lm(price ~ stars * boro + room_type * boro, data = nyc_airbnb) 

fit_interaction %>% 
  broom::tidy()
```

```{r}
nyc_airbnb %>%  
  filter(boro == "Brooklyn") %>%  
  lm(price ~ stars + room_type, data = .) %>% 
  broom::tidy()
```
## Let's try to map this
```{r}
nyc_airbnb %>% 
  nest(data = -boro) %>% 
  mutate(
    models = map(.x = data, ~lm(price ~ stars + room_type, data = .x )), 
    results = map(models, broom::tidy)
  ) %>% 
  select(boro, results) %>% 
  unnest(boro, results)
```

## Let's nest neighborhoods 
```{r}
nyc_airbnb %>% 
  filter (boro == "Manhattan") %>% 
  nest(data = -neighborhood) %>% 
  mutate(
    models = map(.x = data, ~lm(price ~ stars + room_type, data = .x )), 
    results = map(models, broom::tidy)
  ) %>% 
  select(neighborhood, results) %>% 
  unnest(neighborhood, results)
```

```{r}
manhattan_nest_lm_results = 
  nyc_airbnb %>% 
  filter (boro == "Manhattan") %>% 
  nest(data=-neighborhood) %>% 
  mutate(
    models = map(.x = data, ~lm(price ~ stars + room_type, data = .x )), 
    results = map(models, broom::tidy)
  ) %>% 
  select(neighborhood, results) %>% 
  unnest(neighborhood, results)
```

```{r}
manhattan_nest_lm_results %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighborhood, y = estimate)) + 
  geom_point() + 
  facet_wrap(~term) + 
  theme(axis.text.x = element_text(angle = 80, hjust = 1))
```

```{r}
nyc_airbnb %>% 
  filter(neighborhood == "NoHo", room_type == "Shared room")
```




